config/routes.rb
Rails.application.routes.draw do
  devise_for :partners
  devise_for :users
  resources :users, :only => [:show]
  resources :partners, :only => [:show]
  resources :services
 

  root to: "services#index"
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/partner.rb
class Partner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_attached_file :avatar, :styles => { :medium => "300x300>" , :thumb => "50x50#"}, :default_url => "/app/assets/images/thumb/missing.png"
 validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/             
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :partner
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>" , :thumb => "50x50#"}, :default_url => "/app/assets/images/thumb/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
      def configure_permitted_parameters
         devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
         devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password, :avatar])
      end

   
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
	def show
		@partner = Partner.find(params[:id])
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_partner!, except: [:show, :index]

  # GET /services
  # GET /services.json
  def service_params
  params.require(:service).permit(:title, :description, :price, :require, :image)
  end
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @service.partner = current_partner

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:title, :description, :require, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
	 def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeU - Disfruta las mejores experiecnias</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/notification.html.erb" %>

    <%= yield %>
  </body>
</html>

app/views/partials/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">    


<% if !current_user %>
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed pull-right" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>  
    </button>
<% else %>
    <div class="navbar-header pull-left">
<% end %>
    

    <a class="navbar-brand" href="#">BeU</a>
    </div>


<% if !current_user %>
    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Ayuda</a></li>
        <li><a href="#">Become partner</a></li>
        <!-- <li> <%= link_to "Login", new_user_session_path, class: "item" %></li> -->
        <li><a href="#" data-toggle="modal" data-target="#loginModal">Login</a></li>
        <%= render "devise/sessions/new" %>

        <li class="hidden-lg hidden-md"><a href="#">Download app</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
<% else %>
    <div class="nav navbar-header pull-right ">
      <ul class="nav navbar-nav pull-left hidden-xs">
        <li><a href="#">Ayuda</a></li>
        <li><a href="#">Become Partner</a></li>
      </ul>
      <ul class="nav pull-left">
        <li class="pull-left">
          <a href="#"><span class="glyphicon glyphicon-inbox"></span></a>
        </li>
        <li class="pull-left">
          <a href="#"><span class="glyphicon glyphicon-globe"></span></a>
        </li>
        <li class="dropdown pull-left">
          <a href="#" class="dropdown-toogle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span></a>
          <ul class="dropdown-menu pull-right" id="dropdown-navbar">
            <li><a href="#">Tus tickets</a></li>
            <li><a href="#">Wichlist</a></li>
            <li class="hidden-md hidden-lg"><a href="#">Download app</a></li>
            <li><a href="#">Cuenta</a></li>
            <li><a href="#">Perfil</a></li>
            <li class="divider visible-xs"></li>
            <li class="visible-xs"><a href="#">Become partner</a></li>
            <li class="visible-xs"><a href="#">Help</a></li>
          </ul>
        </li>
      </ul>
    </div>
<% end %>
  

  </div><!-- /.container-fluid-->
</nav>



<% if current_user %>
<%= link_to "logout", destroy_partner_session_path, method: :delete, class: "item" %>
<% end %>
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>
<div class="modal fade" id=myModal " tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- 
<div class="ui stackable container menu" id="nav_bar">
  <div class="item">
    <img src="http://semantic-ui.com/examples/assets/images/logo.png">
  </div>
  <%= link_to "Services", services_path, class: "item" %>
  <div class="menu right">
    <% if current_user %>
      <img  class="ui mini circular image" <%= image_tag(current_user.avatar.url(:thumb)) %>
      <%= link_to current_user.name, current_user %>
      <%= link_to "cuenta",  edit_user_registration_path, class: "item" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
    <% elsif current_partner %>
      <img  class="ui mini circular image" <%= image_tag(current_partner.avatar.url(:thumb)) %>
      <%= link_to current_partner.email, current_partner %>
      <%= link_to "cuenta", edit_partner_registration_path, class: "item" %>
      <%= link_to "logout", destroy_partner_session_path, method: :delete, class: "item" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "item" %>
      <%= link_to "Register", new_user_registration_path, class: "item" %>
      <%= link_to "become Partner", new_partner_registration_path, class: "item" %>
      <%= link_to "login as Partner", new_partner_session_path, class: "item" %>
    <% end %>

  </div>
</div>
 -->

app/views/partials/_notification.html.erb
<% if notice %>
  <div class="ui container">
    <div class="ui segment">
      <div class="ui icon message">
        <i class="info icon"></i>
        <div class="content">
          <div class="header">
            Notice!
          </div>
          <p><%= notice %></p>
        </div>
      </div>
    </div>
  </div>
<% elsif alert %>
  <div class="ui container">
    <div class="ui segment">
      <div class="ui icon message">
        <i class="warning icon"></i>
        <div class="content">
          <div class="header">
            Alert!
          </div>
          <p><%= alert %></p>
        </div>
      </div>
    </div>
  </div>    
<% end %>

app/views/partners/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/partners/show.html.erb
<h1><%= current_partner.email %></h1>

app/views/services/_form.html.erb
<div class="ui attached message">
  <div class="header">
    Send a new Service
  </div>
  <p>Fill out the form in order to send your Service.</p>
</div>

<%= form_for @service, :html => {:class => "ui form attached fluid segment"} do |f| %>

  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :require %>
    <%= f.text_area :require %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_area :price %>
  </div>
  
  <div class="actions">
    <%= f.submit "Submit service", class: "ui blue submit button" %>
  </div>

<% end %>
view raw

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<div>
   <%= render "partials/menu.html.erb" %>
</div>



<div class="container">
  <h1 style="margin-top: 30px">Show services on a nice way</h1>
    <% if current_partner %>
      <%= link_to "New Service", new_service_path, class: "button" %>
    <% end %>
  <div class="relaxed divided items">
    <% @services.each do |service| %>
      <div class="item">
          
        <div class="content">
          <%= link_to service.title, service, class: "header" %>
          <div class="description">
            <%= service.description %>
          </div>
          <div class="Require">
            <%= service.require %>
          </div>
          <div class="description">
            <%= service.price %>
          </div>
         
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/services/new.html.erb
<div class="ui container">
  <%= render "form" %>
</div>

app/views/services/show.html.erb
<div class="ui container">
  <div class="ui relaxed divided items">
    <div class="item">
      
      <div class="content">
        <a class="header"><%= @service.title %></a>
      </div>
        <div class="description">
          <%= @service.description %>
        </div>
        <div class="description">
          <%= @service.price %>
        </div>
        <div class="description">
          <%= @service.require %>
        </div>
        <div class="extra">
          <%= image_tag @service.partner.avatar.url(:thumb), class: "ui circular avatar image" %> <%= @service.partner.email %>
        </div>
          
        <div class="ui labeled button" tabindex="0">
          <div class="ui blue button">
            <i class="heart icon"></i>
          </div>
          <div class="ui basic blue left pointing label">
            101
          </div>
        </div>

      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

app/views/users/show.html.erb
<h1><%= current_user.name %></h1>